#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_presets.h"
#include "special_presets.h"
#include "textures.h"
#include "dialog_ids.h"
#include "game/areamap.h"

#include "make_const_nonconst.h"
#include "levels/castle_grounds/texture.inc.c"
#include "levels/castle_grounds/material.inc.c"
#include "levels/castle_grounds/areas/1/1/model.inc.c"
#include "levels/castle_grounds/areas/1/2/model.inc.c"
#include "levels/castle_grounds/areas/1/3/model.inc.c"
#include "levels/castle_grounds/areas/1/4/model.inc.c"
#include "levels/castle_grounds/areas/1/5/model.inc.c"
#include "levels/castle_grounds/areas/1/6/model.inc.c"

#include "levels/castle_grounds/areas/1/collision.inc.c"
#include "levels/castle_grounds/areas/1/movtext.inc.c"
#include "levels/castle_grounds/areas/1/areamap.inc.c"
