#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_presets.h"
#include "special_presets.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"
#include "levels/castle_inside/texture.inc.c"
#include "levels/castle_inside/material.inc.c"
#include "levels/castle_inside/painting.inc.c"

#include "levels/castle_inside/areas/1/lobby/model.inc.c"
#include "levels/castle_inside/areas/1/bowser_hallway/model.inc.c"
#include "levels/castle_inside/areas/1/mountain_room/model.inc.c"
#include "levels/castle_inside/areas/1/fire_bubble_room/model.inc.c"
#include "levels/castle_inside/areas/1/water_land_room/model.inc.c"
#include "levels/castle_inside/areas/1/snow_slider_room/model.inc.c"
#include "levels/castle_inside/areas/1/hallway/model.inc.c"
#include "levels/castle_inside/areas/1/collision.inc.c"
#include "levels/castle_inside/areas/1/room.inc.c"

#include "levels/castle_inside/trap_door/model.inc.c"
#include "levels/castle_inside/trap_door/collision.inc.c"
