#ifndef SPECIAL_PRESETS_H
#define SPECIAL_PRESETS_H

enum SpecialPresets {
    special_null_start,
    special_yellow_coin,
    special_yellow_coin_2,
    special_unknown_3,
    special_boo,
    special_unknown_5,
    special_lll_drawbridge_spawner,
    special_empty_9,
    special_lll_rotating_block_with_fire_bars,
    special_lll_floating_wood_bridge,
    special_tumbling_platform,
    special_lll_rotating_hexagonal_ring,
    special_lll_sinking_rectangular_platform,
    special_lll_sinking_square_platforms,
    special_lll_tilting_square_platform,
    special_lll_bowser_puzzle,
    special_mr_i,
    special_empty_21,
    special_empty_22,
    special_empty_23,
    special_empty_24,
    special_empty_25,
    special_moving_yellow_coin,
    special_moving_blue_coin,
    special_jrb_chest,
    special_water_ring,
    special_mine,
    special_empty_30,
    special_empty_31,
    special_bowser,
    special_wf_rotating_wooden_platform,
    special_small_bomp,
    special_wf_sliding_platform,
    special_tower_platform_group,
    special_rotating_counter_clockwise,
    special_wf_tumbling_bridge,
    special_large_bomp,

    special_level_geo_03 = 0x65,
    special_level_geo_04,
    special_level_geo_05,
    special_level_geo_06,
    special_level_geo_07,
    special_level_geo_08,
    special_level_geo_09,
    special_level_geo_0A,
    special_level_geo_0B,
    special_level_geo_0C,
    special_level_geo_0D,
    special_level_geo_0E,
    special_level_geo_0F,
    special_level_geo_10,
    special_level_geo_11,
    special_level_geo_12,
    special_level_geo_13,
    special_level_geo_14,
    special_level_geo_15,
    special_level_geo_16,
    special_bubble_tree,
    special_castle_door_warp,
    special_castle_door,
    special_castle_door_A,
    special_castle_door_B,
    special_castle_door_C,
    special_castle_door_D,

    special_null_end = 0xFF
};

#endif // SPECIAL_PRESETS_H
